server:
    port: 8080

spring:
  # データソース定義は省略
  graphql:
    graphiql:
      enabled: true
      path: /graphiqls
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE;MODE=DB2
    username: sa
    password: ''
